// SPDX-License-Identifier: AGPL-3.0-or-later
// Only application resources are listed. ROMs, saves and source archives are excluded.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),files=[];
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name),rel=path.relative(root,p).split(path.sep).join('/');if(e.isDirectory()){if(!['sources','scripts','tests','node_modules','.git','test-results','playwright-report'].includes(e.name))walk(p);}else if((/\.(js|mjs|css|html|json|png|svg|wasm|data|webmanifest|txt|md)$/.test(e.name)||e.name==='LICENSE')&&!['offline-manifest.js','sw.js','RELEASE_CONTENT.json','RELEASE_REVIEW.json'].includes(rel))files.push(rel);}}
walk(root);files.sort();const buildTag=/<meta name="app-build" content="[^"]*">/,placeholder='<meta name="app-build" content="0000000000000000">';
const indexPath=path.join(root,'index.html'),index=fs.readFileSync(indexPath,'utf8');if(!buildTag.test(index))throw Error('Missing app build marker');
const hash=crypto.createHash('sha256');let bytes=0;for(const f of files){const b=f==='index.html'?Buffer.from(index.replace(buildTag,placeholder)):fs.readFileSync(path.join(root,f));hash.update(f);hash.update(b);bytes+=b.length;}hash.update(fs.readFileSync(path.join(root,'sw.js')));
const version=hash.digest('hex').slice(0,16),nextIndex=index.replace(buildTag,`<meta name="app-build" content="${version}">`);
if(process.argv.includes('--check'))require('node:assert/strict').equal(index,nextIndex,'HTML build marker is stale');else fs.writeFileSync(indexPath,nextIndex);
const shell=files.filter(f=>!f.startsWith('vendor/')&&!f.startsWith('assets/skins/')&&!f.startsWith('cores/')&&!f.startsWith('licenses/'));
const content='// Generated by scripts/build-offline.cjs. No user content.\nself.APP_OFFLINE = '+JSON.stringify({version,files,shell,bytes})+';\n';
if(process.argv.includes('--check'))require('node:assert/strict').equal(fs.readFileSync(path.join(root,'offline-manifest.js'),'utf8'),content,'Offline manifest is stale');
else fs.writeFileSync(path.join(root,'offline-manifest.js'),content);
console.log(`Offline manifest: ${files.length} application files, ${(bytes/1048576).toFixed(1)} MiB.`);
