// SPDX-License-Identifier: AGPL-3.0-or-later
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require('./browser-runtime.cjs'),roms=require('./cartridges.cjs');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{}),args:['--autoplay-policy=no-user-gesture-required']});
try{const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postDataBuffer()?.length||0}));
await p.goto(process.env.TEST_URL||'http://127.0.0.1:4173/');await p.getByText('ゲームを追加しましょう').waitFor();
for(const system of ['gba','nes']){const file=path.join(os.tmpdir(),'feature-'+process.pid+'.'+system);fs.writeFileSync(file,roms[system]());try{await p.locator('#rom-input').setInputFiles(file);await p.locator('.game-launch').nth(system==='gba'?0:1).waitFor();}finally{fs.unlinkSync(file);}}
await p.locator('.game-launch').first().click();await p.locator('.game-info-play').click();await p.locator('#loading').waitFor({state:'hidden'});await p.waitForTimeout(300);
await p.locator('#player-menu').click();await p.locator('[data-setting=showFps]').check();await p.locator('[data-setting=filter]').selectOption('edge4x');await p.locator('[data-action=play]').click();await p.waitForTimeout(1400);
assert.deepEqual(await p.locator('#screen canvas').evaluate(c=>[c.width,c.height]),[960,640]);assert.match(await p.locator('#fps-meter').textContent(),/\d+\.\d fps/);console.log('NORMAL',await p.locator('#fps-meter').textContent());
for(let i=0;i<4;i++)await p.locator('#boost').click();await p.waitForTimeout(1800);assert.match(await p.locator('#fps-meter').textContent(),/5(?:倍|×)/);console.log('SPEED',await p.locator('#fps-meter').textContent());await p.locator('#boost').click();assert.equal(await p.locator('#boost').textContent(),'1×');
await p.locator('#player-menu').click();await p.locator('[data-action=cheats]').click();await p.locator('#cheat-type').selectOption('4');await p.locator('#cheat-name').fill('Synthetic red pixel');await p.locator('#cheat-code').fill('06000000:001F');await p.locator('#cheat-add').click();await p.locator('[data-cheat-toggle="0"]').waitFor();await p.locator('#close-sheet').click();await p.waitForTimeout(250);
const rgba=await p.locator('#screen canvas').evaluate(c=>[...c.getContext('2d').getImageData(0,0,1,1).data]);assert.ok(rgba[0]>200&&rgba[1]<10&&rgba[2]<10,'Cheat did not affect VRAM: '+rgba);console.log('PASS: VBA cheat changes synthetic pixel.');
await p.locator('#player-menu').click();await p.locator('[data-action=exit]').click();await p.locator('#player').waitFor({state:'hidden'});
// Hold the real worker's status request until the UI is inspected: an early
// download click must never be accepted before its handler is installed.
await p.evaluate(()=>{const send=ServiceWorker.prototype.postMessage;ServiceWorker.prototype.postMessage=function(message,...rest){if(message?.type==='status'){window.releaseOfflineStatus=()=>{ServiceWorker.prototype.postMessage=send;send.call(this,message,...rest);};return;}return send.call(this,message,...rest);};});
await p.locator('[data-tab=settings]').click();await p.locator('[data-action=offline]').click();await p.waitForFunction(()=>typeof window.releaseOfflineStatus==='function');assert.equal(await p.locator('#offline-download').isDisabled(),true,'Wait for the initial status before accepting input');await p.evaluate(()=>window.releaseOfflineStatus());await p.locator('#offline-download').click();await p.getByText('オフラインで遊べます。',{exact:true}).waitFor({timeout:120000});await p.locator('#close-sheet').click();
await c.setOffline(true);await p.reload();await p.locator('.settings-page').waitFor();assert.equal(new URL(p.url()).hash,'#settings','Offline reload retains the settings route');await p.locator('[data-tab=games]').click();await p.locator('.game-launch').first().click();await p.locator('.game-info-play').click();await p.locator('#loading').waitFor({state:'hidden'});await p.waitForTimeout(300);
assert.deepEqual(await p.locator('#screen canvas').evaluate(c=>[c.width,c.height]),[960,640]);const offlinePixel=await p.locator('#screen canvas').evaluate(c=>[...c.getContext('2d').getImageData(0,0,1,1).data]);assert.ok(offlinePixel[0]>200&&offlinePixel[1]<10);console.log('PASS: fully offline reload, 64MiB ROM launch and persistent enabled cheat.');
await p.locator('#player-menu').click();await p.locator('[data-action=cheats]').click();await p.locator('[data-cheat-toggle="0"]').uncheck();await p.locator('[data-cheat-toggle="0"]:not(:checked)').waitFor();await p.locator('[data-cheat-delete="0"]').click();await p.locator('[data-cheat-toggle="0"]').waitFor({state:'detached'});await p.locator('#close-sheet').click();await p.locator('#player-menu').click();await p.locator('[data-action=exit]').click();await p.locator('#player').waitFor({state:'hidden'});
await p.locator('.game-launch').nth(1).click();await p.locator('.game-info-play').click();await p.locator('#loading').waitFor({state:'hidden',timeout:60000});assert.equal(await p.locator('#screen canvas').count(),1);console.log('PASS: previously unplayed NES core starts offline; cheat disable/delete.');
const net=requests.filter(r=>/^https?:/.test(r.url));assert.ok(net.every(r=>r.url.startsWith(process.env.TEST_URL||'http://127.0.0.1:4173/')&&['GET','HEAD'].includes(r.method)&&!r.body));assert.deepEqual(errors,[]);console.log('PASS: no external HTTP / upload / runtime error.');
await p.goto('about:blank');await c.close();}finally{await Promise.race([b.close(),new Promise(r=>setTimeout(r,2500))]);}})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
