// SPDX-License-Identifier: AGPL-3.0-or-later
// Original in-memory test images, never copyrighted game/controller artwork.
const assert=require('node:assert/strict'),zlib=require('node:zlib');
const {chromium}=require('./browser-runtime.cjs');
function crc(b){let c=0xffffffff;for(const n of b){c^=n;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(files){let chunks=[],central=[],offset=0;for(const[name,bytes]of Object.entries(files)){const data=Buffer.from(bytes),packed=zlib.deflateRawSync(data),n=Buffer.from(name),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(8,8);h.writeUInt32LE(crc(data),14);h.writeUInt32LE(packed.length,18);h.writeUInt32LE(data.length,22);h.writeUInt16LE(n.length,26);chunks.push(h,n,packed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(8,10);c.writeUInt32LE(crc(data),16);c.writeUInt32LE(packed.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+packed.length;}const end=Buffer.alloc(22),dir=Buffer.concat(central);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(dir.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...chunks,dir,end]);}
function pdf(){let s='%PDF-1.4\n',offset=[0];const stream='0.1 0.2 0.3 rg 0 0 390 844 re f\n';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 390 844] /Resources << >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}endstream`];objects.forEach((o,i)=>{offset.push(s.length);s+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=s.length;s+='xref\n0 5\n0000000000 65535 f \n'+offset.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(s);}
(async()=>{const b=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage(),requests=[],errors=[];p.on('request',r=>requests.push(r));p.on('console',m=>{if(m.type()==='error')console.log(m.text());});p.on('pageerror',e=>errors.push(e.message));const base=process.env.TEST_URL||'http://127.0.0.1:4173/';await p.goto(base);await p.locator('[data-tab=settings]').click();await p.locator('[data-action=skins]').click();
 const rep={mappingSize:{width:390,height:844},assets:{resizable:'controller.pdf'},gameScreenFrame:{x:20,y:65,width:350,height:233},items:[{inputs:['a'],frame:{x:279,y:513,width:76,height:64}}]};
 const info={name:'Original PDF fixture',gameTypeIdentifier:'com.rileytestut.Delta.game.gba',representations:{iphone:{standard:{portrait:rep}}}};
 const payload=zip({'info.json':JSON.stringify(info),'controller.pdf':pdf()});await p.locator('#import-skin').click();await p.locator('#skin-input').setInputFiles({name:'local-fixture.deltaskin',mimeType:'application/zip',buffer:payload});await p.locator('#skin-select option',{hasText:'Original PDF fixture'}).waitFor({state:'attached',timeout:30000});
 const converted=await p.evaluate(async()=>{const db=await import('./src/storage.js');const v=(await db.all('skins'))[0];return{type:v.images['controller.pdf'].type,size:v.images['controller.pdf'].size,frame:v.portrait.screens[0].outputFrame};});assert.equal(converted.type,'image/png');assert.ok(converted.size>0);assert.equal(converted.frame.width,350);
 const wrongGame=await p.evaluate(async bytes=>{const{importSkin}=await import('./src/skins.js');try{await importSkin(new File([new Uint8Array(bytes)],'wrong-game.deltaskin'),'snes');return false;}catch(e){return e.message==='このゲーム用のスキンではありません。';}},[...payload]);assert.equal(wrongGame,true);
 const malicious=zip({'../info.json':'{}'});assert.equal(await p.evaluate(async bytes=>{const{readSkinZip}=await import('./src/skin-zip.js');try{await readSkinZip(new Uint8Array(bytes).buffer);return false;}catch{return true;}},[...malicious]),true);
 for(const name of ['not-a-skin.txt','game.gba'])assert.equal(await p.evaluate(async({name,bytes})=>{const{importSkin}=await import('./src/skins.js');try{await importSkin(new File([new Uint8Array(bytes)],name));return false;}catch(e){return e.message.includes('スキンを選択');}},{name,bytes:[...payload]}),true,'Reject non-skin extensions even if their contents look like a skin ZIP');
 const evil={...info,representations:{iphone:{standard:{portrait:{...rep,assets:{resizable:'https://example.com/a.png'}}}}}};const bad=zip({'info.json':JSON.stringify(evil),'controller.pdf':pdf()});assert.equal(await p.evaluate(async bytes=>{const{importSkin}=await import('./src/skins.js');try{await importSkin(new File([new Uint8Array(bytes)],'bad.deltaskin'));return false;}catch{return true;}},[...bad]),true);
 await p.locator('#close-sheet').click();await p.screenshot({path:process.env.SCREENSHOT_PATH||require('node:os').tmpdir()+'/local-play-settings.png'});
 assert.deepEqual(errors,[]);assert.ok(requests.filter(r=>/^https?:/.test(r.url())).every(r=>new URL(r.url()).origin===new URL(base).origin&&r.method()==='GET'&&!r.postData()));console.log('PASS: local ZIP import, PDF rasterization, legacy Delta layout, path/external asset rejection, no uploads.');await c.close();}finally{await Promise.race([b.close(),new Promise(r=>setTimeout(r,2000))]);}})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
